module.exports = {
    recno: 3,
    animal_status: 5,
    status_in_farm: 5,
    matricol_number: 10,
    short_number: 7,
    internal_number: 7, 
    birth_date: 7,
    sire: 11,
    dam: 11,
    maternal_sire: 11,
    parity: 4,
    last_calving_date: 7,
    breed: 8,   
    actions: 4,
}